### ISSUE TITLE
Issue on "README.md"

### ISSUE THREAD

**Issue by Panquesito7** [TumeniNodes/old-pkarcs-do-not-use#7]
It should be `Requirements` and not `Requierments`.
Could you fix that, please?

**Comment by TumeniNodes** [comment]
I have some tough news for you...
I've turned this into a modpack xD
I will be deleting this repo and uploading the new one soon.

I will put this original aside on my local drive so we can figure out which portions of the work you did can be saved/split up into each of the three mods.

Actually, maybe a better idea... is to simply rename this repo and keep it around until the documents bits are sorted out.

PS
 I also finally fixed the sounds for the pkarcs' nodes. They were not using the group sounds when breaking, which annoyed me for so long, but I never took the time to look things over till now... it was merely the matter of a single, missing 'S' in the code :P 

init.lua at line L303 node_def.sound should have been node_def.sounds

**Comment by Panquesito7** [comment]
I was just doing a PR and you did new commits, so, I re-forked it again. 😋
**EDIT:** I've created the PR now.

BTW, very nice news. Love the new screenshots!
P.S.: Hey, you might want to make this repository read-only, as it is old, and shouldn't be used anymore.

I will close this issue, as this is getting off-topic (and this mod will be no longer used).
Thank you, anyway. 🙂

**Comment by TumeniNodes** [comment]
heh, sorry bout that.
I'm done for the moment with pushes. 
I kept messing up the screenshots, trying to rush and do several tasks here at the homested

the old repo will be deleted in the next day or so...
This one I will add to ContentDB later tonight (after I merge your PRs of course)

**Comment by Panquesito7** [comment]
> heh, sorry bout that.

Don't worry, it's ok. I just realized so late, so, it was also my fault.

> the old repo will be deleted in the next day or so...
> This one I will add to ContentDB later tonight (after I merge your PRs of course).

Very well!
